### ISSUE TITLE
White background.png image on the HTML body

### ISSUE THREAD

**Issue by sproclavism** [rafalfr/smarttrafficmeter#1]
First of all, great job on creating this. It perfectly fits my needs.

I noticed that on _some_ pages a white background.png is set as the background.
I have a very short question: is it serving any purpose?

The reason I ask is because it is messing with my extensions providing dark theme modifications.
some examples:
* [data page](https://user-images.githubusercontent.com/8351931/211212332-845d1e41-5fa2-4450-87bb-3d5c51817c16.png) (no background.png set)
* [home](https://user-images.githubusercontent.com/8351931/211212441-ca2d72c6-6b7d-42e9-a164-6dfb3d541c29.png) (background.png set)
* [settings](https://user-images.githubusercontent.com/8351931/211212467-a75bc916-0b42-4523-8d30-7be37550195b.png) (background.png set)

I understand this is not an issue with stm itself, but in the case that this background doesn't serve a purpose, would removing it be a possibility?

Thank you

**Comment by rafalfr** [comment]
Ok, I will change this soon.

**Comment by rafalfr** [comment]
I have already updated the program. Please let me know if everything is all right now.

**Comment by sproclavism** [comment]
Hi Raf, I've just updated to the latest version to check, and things are looking good.
Thanks a lot for abiding my trivial request!
